[package]
name = "crdmon"
version = "0.1.0"
edition = "2021"
authors = [
  "Klaus Wagner <klaus.wagner@erstegroup.com>",
]

[dependencies]
kube = { version = "0.76.0", default-features = true, features = ["derive", "runtime", "rust-tls"] } # Library for talking to Kubernetes API

[dev-dependencies]
tokio = { version = "1.14.0", features = ["full"] }
